export const COMPANY_NAME ='Infosys Ltd.';

export const COMPANY_MOTO = 'Powered by Intellect Driven by Values';

export const  COMPANY_ESTABLISH_DATE = 'Since 2 Jul, 1981'

export const EMPLOYEE_ACTION_PENDING = 'EMPLOYEE_ACTION_PENDING'

export const EMPLOYEE_ACTION_SUCCESS = 'EMPLOYEE_ACTION_SUCCESS'

export const EMPLOYEE_ACTION_FAILURE = 'EMPLOYEE_ACTION_FAILURE'

export const EMPLOYEE_ACTION_SEARCH = 'EMPLOYEE_ACTION_SEARCH'

